"""Build a portable Phase 1 benchmark dashboard, tables, plots and reference kit."""
import json, csv, html, shutil, sys
from pathlib import Path
O=Path(sys.argv[1]) if len(sys.argv)>1 else Path('outputs/moin-2025-analysis/phase1-benchmark')
d=json.loads((O/'results.json').read_text());names={'whole':'Whole image','crop384':'10% crop → 384²','crop_native':'10% crop · native'}
metrics=[('rgb_edge_f1','RGB-edge F1','Higher edge agreement; not leaf accuracy'),('flip_ari','Flip partition agreement','Higher is more consistent'),('flip_feature_nrmse','Flip feature difference','Lower is more consistent'),('seam_ratio','Crop-border excess','1 = no excess; not an accuracy score'),('boundary_density','Boundary density','Descriptive; no preferred direction'),('effective_clusters','Effective occupied clusters','Descriptive; flags trivial partitions')]
def v(r,m,key,k=6):
 q=r['methods'][m];c=q['k'][str(k)]
 return q['seam']['ratio'] if key=='seam_ratio' else c['rgb_edge']['f1'] if key=='rgb_edge_f1' else c[key] if key in c else q[key]
with (O/'metrics.csv').open('w',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=['image_id','site','session','method','k','reference_split']+[x[0] for x in metrics]+['encoding_seconds','peak_gpu_mib']);w.writeheader()
 for r in d['images']:
  for m in names:
   for k in [4,6,8]:w.writerow({'image_id':r['id'],'site':r['site'],'session':r['session'],'method':m,'k':k,'reference_split':r['reference_split'],**{key:v(r,m,key,k) for key,_,_ in metrics},'encoding_seconds':r['methods'][m]['encoding_seconds'],'peak_gpu_mib':r['methods'][m]['peak_gpu_mib']})
summary=''
for key,label,note in metrics:
 cells=''.join(f'<td><b>{d["summary"][key][m]["mean"]:.3f}</b><br><small>{d["summary"][key][m]["block_bootstrap_mean_ci95"][0]:.3f}–{d["summary"][key][m]["block_bootstrap_mean_ci95"][1]:.3f}</small></td>' for m in names)
 summary+=f'<tr><th>{label}<br><small>{note}</small></th>{cells}</tr>'
contrasts=''.join(f'<tr><td>{next((a[1] for a in metrics if a[0]==r["metric"]),r["metric"])}</td><td>{names[r["b"]]} − {names[r["a"]]}</td><td>{r["mean_difference"]:+.3f}</td><td>{r["ci95"][0]:+.3f} to {r["ci95"][1]:+.3f}</td></tr>' for r in d['paired_contrasts'] if r['metric'] in [x[0] for x in metrics])
cal=json.loads((O/'runtime_calibration.json').read_text()) if (O/'runtime_calibration.json').exists() else {'images':[]}
runtime=''.join(f'<tr><td>{names[m]}</td><td>{sum(r["methods"][m]["encoding_seconds"] for r in cal["images"])/max(1,len(cal["images"])):.3f} s</td><td>{max([r["methods"][m]["peak_gpu_mib"] for r in cal["images"]] or [0]):.0f} MiB</td></tr>' for m in names)
note='Complete' if d['complete'] else 'PARTIAL — still running'
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phase 1 · DINOv3 benchmark</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f5ef;color:#213b32;font:16px/1.55 system-ui,sans-serif}main{max-width:1480px;margin:auto;padding:34px}h1{font-size:clamp(32px,4vw,58px);line-height:1.1;margin:14px 0}h2{font-size:25px}h3{font-size:18px}.eyebrow{font-size:13px;letter-spacing:.16em;text-transform:uppercase}.lead{max-width:1050px}.panel{background:white;border:1px solid #d4dfd2;border-radius:13px;padding:23px;margin:22px 0}.note{border-left:4px solid #668d71;padding:12px 16px;background:#e8eee2}table{width:100%;border-collapse:collapse;font-size:14px}th,td{border-bottom:1px solid #d8e1d5;padding:11px;text-align:left}small,.small{font-size:12px;color:#5e7467;font-weight:400}.scroll{overflow-x:auto}.controls{display:flex;gap:15px;flex-wrap:wrap;align-items:center;margin:15px 0}select,button,input{font:inherit;padding:7px;border:1px solid #b4c4b5;border-radius:5px;background:white}button{cursor:pointer}a{color:#276b4e}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}figure{margin:0;min-width:0}figure img{width:100%;display:block}figcaption{font-size:13px;margin-bottom:8px}summary{cursor:pointer;font-weight:650}details{margin:16px 0}#plot{width:100%;height:360px}code{font-size:13px;overflow-wrap:anywhere}@media(max-width:800px){main{padding:14px}.panel{padding:14px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:450px){.grid{grid-template-columns:1fr}}
</style><main><div class="eyebrow">Phase 1 · reproducible baseline · VERSION</div><h1>Measure detail.<br>Check stability. Expose artifacts.</h1><div class="lead"><p><b>STATE · COUNT / TOTAL unique photographs · four sites.</b> The 444 archive entries contain 439 distinct photos. All three strategies are evaluated on the same saved working images, with paired original and horizontally reflected inference passes.</p><p class="note"><b>Automatic diagnostics are complete; leaf accuracy is not measured.</b> RGB-edge agreement, reflection consistency and crop-border excess are different properties. They cannot establish leaf-instance IoU or justify one overall “accuracy” score. Forty reference windows are prepared for independent review; none has been annotated yet.</p><p>Phase 1 visual assessment favored enlarged 10% crops for individual-leaf detail. This benchmark tests related measurable properties without treating that assessment as ground truth. Existing biodiversity scores and the earlier comparison remain unchanged.</p><p><a href="metrics.csv">Per-image metrics CSV</a> · <a href="results.json">Complete results</a> · <a href="protocol.json">Frozen protocol</a> · <a href="README.md">Reproduce / extend</a> · <a href="reference-kit/index.html">Reference windows</a></p></div>
<section class="panel"><h2>Three methods, separate clustering fits</h2><p>Identical crop geometry for both crop methods; raw DINOv3 features; one shared PCA16 basis per photograph; separate K-means at K=4,6,8. No AnyUp, flip averaging or shifted-grid averaging. Horizontal reflection is an independent test, not part of the prediction ensemble.</p><div class="scroll"><table><thead><tr><th>Metric · K=6 where applicable</th><th>Whole image</th><th>10% crop → 384²</th><th>10% crop · native</th></tr></thead><tbody>SUMMARY</tbody></table></div><p class="small">Means across all photographs; intervals are 95% site/session-block bootstrap intervals for the mean (2,000 draws, BLOCKS blocks). Repeated physical plots across sessions may still correlate. Image size and scene/view variation remain part of this collection. No winner is assigned by combining these diagnostics.</p><details><summary>Paired differences between methods</summary><div class="scroll"><table><thead><tr><th>Metric</th><th>B − A</th><th>Mean difference</th><th>95% block interval</th></tr></thead><tbody>CONTRASTS</tbody></table></div></details></section>
<section class="panel"><h2>Explore variation and K sensitivity</h2><div class="controls"><label>Metric <select id="metric">METRIC_OPTIONS</select></label><label>K <select id="k"><option>4</option><option selected>6</option><option>8</option></select></label><label>Site <select id="site"><option value="">All sites</option><option value="fessbach">Feßbach</option><option value="heidesheim">Heidesheim</option><option value="rettmer">Rettmer</option><option value="ribbeck">Ribbeck</option></select></label></div><p id="metricnote"></p><svg id="plot" viewBox="0 0 1000 360" role="img" aria-label="Per-image metric values for the three methods"></svg><p class="small">Each dot is one photo; bars mark the mean of the selected photos. Distribution plots describe observed variation, not confidence intervals. Click a dot to inspect that photograph.</p><div class="controls"><label>Photo <select id="photo"></select></label><label>Display <select id="layer"><option value="pca">Shared PCA colors</option><option value="overlay">Separate K=6 overlays</option></select></label></div><div id="inspect"></div></section>
<section class="panel"><h2>Reference accuracy: ready for annotation</h2><p>Forty 256 × 256 windows were selected independently of output scores: ten per site, half from development sessions and half from sessions reserved for future reference evaluation. Empty masks are explicitly all-ignore, not background. The evaluator refuses unreviewed or empty reference masks.</p><p>Reviewed leaf masks enable boundary precision/recall/F1 for the existing appearance partitions. Leaf-instance IoU additionally requires actual leaf-instance predictions; K-means colors are not automatically counted as leaves. Future IoU uses one-to-one mask matching and accounts for missed leaves.</p><p><a href="reference-kit/index.html">Browse the 40 windows</a> · <a href="reference-kit/references.json">Annotation manifest</a> · <a href="reference-kit/README.md">Annotation rules</a> · <a href="score_leaf_references.py">Reference evaluator</a></p><p class="small">These reserved sessions are not fully blind: automatic metrics are visible, and some photographs may have been inspected in earlier work. Use genuinely unseen images for a final external validation claim.</p></section>
<section class="panel"><h2>Runtime calibration</h2><div class="scroll"><table><thead><tr><th>Method</th><th>Mean encoding time</th><th>Maximum allocated GPU memory</th></tr></thead><tbody>RUNTIME</tbody></table></div><p class="small">Four isolated Feßbach smoke-test images on the existing RTX 4000 SFF Ada. DINO extraction only; includes preprocessing/token transfer, excludes shared PCA and clustering. Main benchmark uses four concurrent workers, so its per-image runtime records include contention and are not used for isolated speed comparisons.</p></section>
<section class="panel"><h2>What each measurement can establish</h2><ul><li><b>RGB-edge F1:</b> boundary agreement with the strongest 15% of grayscale Sobel gradients after σ=1 smoothing, within 2 working pixels. Veins/shadows/soil also create edges; weak leaf boundaries may be missed. This is not IoU against botanical truth.</li><li><b>Flip ARI:</b> original clusters compared with clusters predicted from reflected input, transformed back, using the same fitted centers. Label-permutation invariant; stable trivial outputs can score well.</li><li><b>Flip feature difference:</b> RMS change in the shared PCA16 field divided by the pooled PCA standard deviation. Lower is more stable, not necessarily more informative.</li><li><b>Crop-border excess:</b> feature jumps along crop starts/ends relative to off-border jumps matched by RGB contrast decile and orientation. Whole-image fields use the same hypothetical lines. A ratio near 1 cannot rule out broader periodic textures inside crops.</li><li><b>Boundary density / effective clusters:</b> descriptive checks against falsely rewarding overly smooth or trivial partitions. These are not leaf counts.</li></ul><p>All evaluation excludes recorded artifacts plus a 16-pixel margin around them and image borders. Source artifact annotations are incomplete; quadrat rods, labels and shadows may remain. No vegetation mask is used.</p></section></main><script>
const D=DATA,NAMES={whole:'Whole image',crop384:'10% crop → 384²',crop_native:'10% crop · native'},METHODS=Object.keys(NAMES),META=METADATA;
const $=s=>document.querySelector(s);let selected=D.images[0].id;
function value(r,m,key,k){const q=r.methods[m],c=q.k[k];return key==='seam_ratio'?q.seam.ratio:key==='rgb_edge_f1'?c.rgb_edge.f1:(key in c?c[key]:q[key]);}
function inspect(){const r=D.images.find(r=>r.id===$('#photo').value);if(!r)return;selected=r.id;const layer=$('#layer').value;$('#inspect').innerHTML=`<h3>${r.id} · ${r.site} · ${r.session}</h3><p class="small">${r.size.join(' × ')} px · crop ${r.crop}px · ${r.crop_count} tiles · reference split: ${r.reference_split}. Displayed cluster overlays always use K=6.</p><div class="grid"><figure><figcaption>Input photograph</figcaption><a href="${r.id}/original.jpg" target="_blank"><img src="${r.id}/original.jpg" alt="${r.id} input"></a></figure>${METHODS.map(m=>`<figure><figcaption>${NAMES[m]}</figcaption><a href="${r.id}/${m}_${layer}.jpg" target="_blank"><img src="${r.id}/${m}_${layer}.jpg" alt="${r.id} ${m}"></a></figure>`).join('')}</div>`;}
function update(){const rows=D.images.filter(r=>!$('#site').value||r.site===$('#site').value),key=$('#metric').value,k=$('#k').value;$('#photo').innerHTML=rows.map(r=>`<option>${r.id}</option>`).join('');if(rows.some(r=>r.id===selected))$('#photo').value=selected;$('#metricnote').textContent=META.find(a=>a[0]===key)[2];let vals=rows.flatMap(r=>METHODS.map(m=>value(r,m,key,k))).filter(Number.isFinite),lo=Math.min(0,...vals),hi=Math.max(...vals);if(hi===lo)hi=lo+1;hi+=(hi-lo)*.08;const yy=v=>300-(v-lo)/(hi-lo)*270;let svg='';for(let i=0;i<6;i++){const v=lo+(hi-lo)*i/5,y=yy(v);svg+=`<line x1="70" x2="965" y1="${y}" y2="${y}" stroke="#dde5dc"/><text x="60" y="${y+4}" text-anchor="end" font-size="12">${v.toFixed(2)}</text>`;}METHODS.forEach((m,j)=>{const x=220+j*300,vs=[];rows.forEach((r,i)=>{const v=value(r,m,key,k);if(!Number.isFinite(v))return;vs.push(v);const jitter=(((i*37+13)%101)/100-.5)*105;svg+=`<circle tabindex="0" role="button" aria-label="Inspect ${r.id}" data-id="${r.id}" cx="${x+jitter}" cy="${yy(v)}" r="3" fill="${['#507da1','#429170','#b68545'][j]}" opacity=".45"><title>${r.id}: ${v.toFixed(3)}</title></circle>`;});const avg=vs.reduce((a,b)=>a+b,0)/vs.length;svg+=`<line x1="${x-65}" x2="${x+65}" y1="${yy(avg)}" y2="${yy(avg)}" stroke="#20392e" stroke-width="3"/><text x="${x}" y="335" text-anchor="middle" font-size="15">${NAMES[m]}</text>`;});$('#plot').innerHTML=svg;$('#plot').querySelectorAll('[data-id]').forEach(el=>{const fn=()=>{$('#photo').value=el.dataset.id;inspect();};el.addEventListener('click',fn);el.addEventListener('keydown',e=>{if(e.key==='Enter')fn();});});inspect();}
['#metric','#k','#site'].forEach(s=>$(s).addEventListener('change',update));$('#photo').addEventListener('change',inspect);$('#layer').addEventListener('change',inspect);update();
</script></html>'''
replacements={'VERSION':d['version'],'STATE':note,'COUNT':str(d['completed']),'TOTAL':str(d['total']),'SUMMARY':summary,'BLOCKS':str(d['blocks']),'CONTRASTS':contrasts,'RUNTIME':runtime,'METRIC_OPTIONS':''.join(f'<option value="{k}">{label}</option>' for k,label,_ in metrics),'METADATA':json.dumps(metrics),'DATA':json.dumps(d,ensure_ascii=False)}
for k in ['VERSION','STATE','COUNT','TOTAL','SUMMARY','BLOCKS','CONTRASTS','RUNTIME','METRIC_OPTIONS','METADATA','DATA']:page=page.replace(k,replacements[k])
page=page.replace('Displayed cluster overlays always use K=6.', 'Displayed cluster overlays always use K=6. Cluster colors are arbitrary within each method; PCA colors share a basis within this photo.')
page=page.replace('Label-permutation invariant; stable trivial outputs can score well.', 'Label-permutation invariant; stable trivial outputs can score well. For future flip-ensemble methods this is not a held-out transformation; add an independent robustness check or reviewed leaf boundaries.')
if d['complete']:page=page.replace('<h2>Explore variation and K sensitivity</h2>', '<p><a href="diagnostic_summary.png">Download summary PNG</a> · <a href="diagnostic_summary.svg">SVG</a> · <a href="diagnostic_summary.pdf">PDF</a></p><h2>Explore variation and K sensitivity</h2>')
if not d['complete']:page=page.replace('Automatic diagnostics are complete;', 'Automatic diagnostics are still running;')
(O/'index.html').write_text(page,encoding='utf-8')
kit=O/'reference-kit';spec=json.loads((kit/'references.json').read_text());cards=''.join(f'<figure><img src="{r["image"]}" width="256" height="256"><figcaption>{r["id"]} · {r["site"]}<br>{r["split"]} · unreviewed</figcaption></figure>' for r in spec['windows']);(kit/'index.html').write_text('<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reference annotation windows</title><style>body{font:16px system-ui;background:#f4f5ef;padding:25px;color:#20392e}.grid{display:flex;flex-wrap:wrap;gap:15px}figure{margin:0;background:white;padding:12px}figcaption{font-size:12px;max-width:256px}a{color:#276b4e}</style><a href="../index.html">← Benchmark</a><h1>40 reference windows · not yet annotated</h1><p>All mask templates contain ignore pixels. No accuracy scores are available until references are reviewed. <a href="README.md">Annotation rules</a></p><div class="grid">'+cards+'</div>',encoding='utf-8')
print('DASHBOARD',O/'index.html')
